default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV["DB_URL"] || '127.0.0.1' %>
  port: <%= ENV["DB_PORT"] || '5432' %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  #TODO when using my own private database instance, turn on autovacuum/autoanalyse, and use pgtune ### http://pgtune.leopard.in.ua/

development:
  <<: *default
  database: nextvisit_dev

test:
  <<: *default
  database: nextvisit_test

staging:
  <<: *default
  database: nextvisit_staging
  sslmode: require

production_clone:
  <<: *default
  database: nextvisit_prod
  sslmode: require

production:
  <<: *default
  database: nextvisit_prod
  sslmode: require
